/**
 * HedoneAttachDTO.h
 *
 * This file was auto-generated by rest-apigen.
 * Do not modify this file.
 */


#import <Foundation/Foundation.h>

@interface HedoneAttachDTO:NSObject
@property (nonatomic, assign) long long sid;
@property (nonatomic, assign) long long dataId;
@property (nonatomic, copy) NSString * addr;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int index;
@property (nonatomic, copy) NSString * desp;
@property (nonatomic, assign) long long createTime;
@property (nonatomic, assign) long long updateTime;

@end