/**
 * HedoneClassWeeklyTaskResponse.m
 *
 * This file was auto-generated by rest-apigen.
 * Do not modify this file.
 */


#import "HedoneClassWeeklyTaskResponse.h"

@implementation HedoneClassWeeklyTaskResponse
@synthesize sid;
@synthesize title;
@synthesize content;
@synthesize senderId;
@synthesize senderName;
@synthesize senderPicture;
@synthesize updateTime;
//
//+ (NSDictionary *)replacedKeyFromPropertyName{
//	return @{@"sid" : @"id"};
//}
//
//+ (NSDictionary *)objectClassInArray{
//	return @{@"attachs":[HedoneAttachDTO class], @"replys":[HedoneClassWeeklyTaskReplyDTO class]};
//}

@end