/**
 * HedoneAttachDTO.m
 *
 * This file was auto-generated by rest-apigen.
 * Do not modify this file.
 */


#import "HedoneAttachDTO.h"

@implementation HedoneAttachDTO
@synthesize sid;
@synthesize dataId;
@synthesize addr;
@synthesize type;
@synthesize index;
@synthesize desp;
@synthesize createTime;
@synthesize updateTime;

@end