/**
 * HedoneClassWeeklyTaskResponse.h
 *
 * This file was auto-generated by rest-apigen.
 * Do not modify this file.
 */


#import <Foundation/Foundation.h>
#import "HedoneAttachDTO.h"


@interface HedoneClassWeeklyTaskResponse:NSObject
@property (nonatomic, assign) long long sid;
@property (nonatomic, copy) NSString * title;
@property (nonatomic, copy) NSString * content;
@property (nonatomic, strong) NSArray * attachs;
@property (nonatomic, assign) long long senderId;
@property (nonatomic, copy) NSString * senderName;
@property (nonatomic, copy) NSString * senderPicture;
@property (nonatomic, assign) long long updateTime;

@end